#!/bin/bash
set -e

# Certificate generation script for S.A.K.I.N. mTLS
# Generates CA certificate and service certificates for development

CERT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DAYS_VALID=365
KEY_SIZE=2048

echo "Generating S.A.K.I.N. certificates in ${CERT_DIR}"
cd "${CERT_DIR}"

# Generate CA key and certificate
echo "Generating CA certificate..."
openssl genrsa -out ca.key ${KEY_SIZE}
openssl req -new -x509 -days ${DAYS_VALID} -key ca.key -out ca.crt \
    -subj "/C=TR/ST=Istanbul/L=Istanbul/O=S.A.K.I.N./OU=Security/CN=SAKIN Root CA"

# Service names
services=(
    "sakin-ingest"
    "sakin-correlation"
    "sakin-panel-api"
    "sakin-soar"
    "sakin-enrichment"
    "sakin-collectors"
)

# Generate service certificates
for service in "${services[@]}"; do
    echo "Generating certificate for ${service}..."
    
    # Generate private key
    openssl genrsa -out ${service}.key ${KEY_SIZE}
    
    # Generate CSR
    openssl req -new -key ${service}.key -out ${service}.csr \
        -subj "/C=TR/ST=Istanbul/L=Istanbul/O=S.A.K.I.N./OU=${service}/CN=${service}"
    
    # Create extensions file for SAN
    cat > ${service}.ext <<EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = ${service}
DNS.2 = ${service}.sakin.svc.cluster.local
DNS.3 = localhost
IP.1 = 127.0.0.1
EOF
    
    # Sign certificate with CA
    openssl x509 -req -in ${service}.csr -CA ca.crt -CAkey ca.key \
        -CAcreateserial -out ${service}.crt -days ${DAYS_VALID} \
        -extfile ${service}.ext
    
    # Cleanup
    rm ${service}.csr ${service}.ext
    
    echo "  ✓ ${service}.crt and ${service}.key generated"
done

# Generate PKCS12 bundles (for Java/C# apps)
for service in "${services[@]}"; do
    echo "Creating PKCS12 bundle for ${service}..."
    openssl pkcs12 -export -out ${service}.p12 \
        -inkey ${service}.key -in ${service}.crt -certfile ca.crt \
        -password pass:sakin123
    echo "  ✓ ${service}.p12 generated (password: sakin123)"
done

# Create Kubernetes secrets YAML
echo ""
echo "Generating Kubernetes secrets..."
cat > k8s-secrets.yaml <<EOF
# Apply with: kubectl apply -f k8s-secrets.yaml
# Generated by generate-certs.sh on $(date)

---
apiVersion: v1
kind: Namespace
metadata:
  name: sakin
---
EOF

for service in "${services[@]}"; do
    cat >> k8s-secrets.yaml <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: ${service}-tls
  namespace: sakin
type: kubernetes.io/tls
data:
  tls.crt: $(base64 -w 0 ${service}.crt)
  tls.key: $(base64 -w 0 ${service}.key)
  ca.crt: $(base64 -w 0 ca.crt)
---
EOF
done

echo "  ✓ k8s-secrets.yaml generated"

# Set proper permissions
chmod 600 *.key *.p12
chmod 644 *.crt

echo ""
echo "✅ Certificate generation complete!"
echo ""
echo "Files generated:"
echo "  - ca.crt, ca.key (Root CA)"
for service in "${services[@]}"; do
    echo "  - ${service}.crt, ${service}.key, ${service}.p12"
done
echo "  - k8s-secrets.yaml (Kubernetes secrets)"
echo ""
echo "⚠️  WARNING: These are development certificates only!"
echo "   For production, use proper CA (Let's Encrypt, internal PKI, etc.)"
echo ""
echo "Next steps:"
echo "  1. For local dev: Mount this directory as /secrets/certs in containers"
echo "  2. For Kubernetes: kubectl apply -f k8s-secrets.yaml"
echo "  3. Update service configs to enable TLS"
